dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 32
  dataset_path: Pathology:root=/root/data:subset=fold_0
  centering: sinkhorn_knopp
  num_workers: 16
tune:
  tune_every:
  query_dataset_path: KNN:root=/root/data:split=query:subset=fold_0
  test_dataset_path: KNN:root=/root/data:split=test:subset=fold_0
  early_stopping:
    enable: false
student:
  arch: vit_large
  patch_size: 14
  num_register_tokens: 0
  pretrained_weights: 'checkpoints/dinov2_vitl14_pretrain.pth'
  drop_path_rate: 0.4
  ffn_layer: mlp
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 500
  weight_decay_end: 0.2
  base_lr: 2.0e-03 # learning rate for a batch size of 1024, will get scaled in apply_scaling_rules_to_cfg
  warmup_epochs: 80
  layerwise_decay: 1.0
crops:
  local_crops_size: 98
wandb:
  enable: true
  project: 'vision'
  username: 'vlfm'
  exp_name: 'dinov2'
  tags: ['${wandb.exp_name}', 'patch', '${student.arch}']
  dir: '/home/user'
  group:
  resume_id: